//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bashgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class frosh
    {
        public int ID { get; set; }
        public string OzveCode { get; set; }
        public string OzvName { get; set; }
        public string kalaname { get; set; }
        public string PriceKala { get; set; }
        public string tedadkala { get; set; }
        public string Datatarakonesh { get; set; }
    }
}
