//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bashgah
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbBashgahEntities : DbContext
    {
        public DbBashgahEntities()
            : base("name=DbBashgahEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tarakoneshTBl> tarakoneshTBls { get; set; }
        public virtual DbSet<TBkomod> TBkomods { get; set; }
        public virtual DbSet<Tblfrooshgah> Tblfrooshgahs { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<frosh> froshes { get; set; }
    }
}
