//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bashgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarakoneshTBl
    {
        public int ID { get; set; }
        public string Tarakoneshdate { get; set; }
        public string TarakoneshKind { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Price { get; set; }
    }
}
