//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bashgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBkomod
    {
        public int ID { get; set; }
        public string KomodNum { get; set; }
        public string State { get; set; }
        public string Customer { get; set; }
    }
}
