//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bashgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblfrooshgah
    {
        public int ID { get; set; }
        public string KalaName { get; set; }
        public string Price { get; set; }
        public string Mujodi { get; set; }
    }
}
