//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bashgah
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string BirthDate { get; set; }
        public string OzviatDate { get; set; }
        public string EtebarDate { get; set; }
        public string Komod { get; set; }
    }
}
